---
abstract: 'Compatibility layer for Sys::Info'
author:
  - 'Burak Gursoy <burak@cpan.org>'
build_requires:
  Test::More: 0.40
  Test::Sys::Info: 0.20
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3601'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sys-Info-Driver-Unknown
no_index:
  directory:
    - monolithic_version
    - builder
    - t
provides:
  Sys::Info::Driver::Unknown:
    file: lib/Sys/Info/Driver/Unknown.pm
    version: 0.73
  Sys::Info::Driver::Unknown::Device:
    file: lib/Sys/Info/Driver/Unknown/Device.pm
    version: 0.73
  Sys::Info::Driver::Unknown::Device::CPU:
    file: lib/Sys/Info/Driver/Unknown/Device/CPU.pm
    version: 0.73
  Sys::Info::Driver::Unknown::Device::CPU::Env:
    file: lib/Sys/Info/Driver/Unknown/Device/CPU/Env.pm
    version: 0.73
  Sys::Info::Driver::Unknown::OS:
    file: lib/Sys/Info/Driver/Unknown/OS.pm
    version: 0.73
recommends:
  Unix::Processors: 0
requires:
  Sys::Info::Base: 0.73
resources:
  license: http://dev.perl.org/licenses/
  repository: http://bitbucket.org/burak/cpan-sys-info-driver-unknown/
version: 0.73
