#!/usr/bin/perl -w
use strict;
use vars qw(%PREREQ %RECOMMEND %BUILD_REQ);

%BUILD_REQ = (
   'Test::More'      => '0.40',
   'Test::Sys::Info' => '0.13',
);

%PREREQ = (
   'IO::File'        => 0,
   'Sys::Info::Base' => '0.70',
);

%RECOMMEND = (
    'Unix::Processors' => 0,
);

1;
